mode:
  debug: false
messages:
  prefix: "&b&lItemTracker &8» &7"
  no-perm: "You do not have permission for that."
  not-player: "You must be a player to execute this command."
  no-player: "This player is offline or does not exist."
